kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: portworx-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-storage
spec:
  storageClassName: portworx-sc      
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
