apiVersion: v1 
kind: Service
metadata:
  name: gowebapp-mysql
  labels:
    run: gowebapp-mysql
    tier: backend 
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306 
  selector:
    run: gowebapp-mysql
    tier: backend
---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: gowebapp-mysql 
  labels:
    run: gowebapp-mysql
    tier: backend 
spec:
  replicas: 1 
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      run: gowebapp-mysql 
      tier: backend
  template: 
    metadata: 
      labels:
        run: gowebapp-mysql
        tier: backend 
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: px-mysql-snap-clone-2
      containers:
      - name: gowebapp-mysql 
        env:
        - name: MYSQL_ROOT_PASSWORD 
          value: purestorage
        image: jowings/gowebapp-mysql:0.3
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: "/var/lib/mysql"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-io-priority-high
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  priority_io:  "high"

