apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001 
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem   
  accessModes:
  - ReadWriteMany
  - ReadOnlyMany
  nfs: 
    path: /markus1 
    server: 10.226.224.247 
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1 
