apiVersion: v1
kind: Service
metadata:
  name: storage-app-svc
  labels:
    app: storage-app
spec:
  # Make the service externally visible via the node
  type: NodePort

  spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30011
    targetPort: 80
    protocol: TCP
  selector:
    app: storage-app

---

apiVersion: v1
kind: Pod
metadata:
  name: px-pvc-pod
  labels:
    app: storage-app
spec:
  schedulerName: stork
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
  containers:
  - image: tweeksy/file_uploader_demo
    name: pvc-container
    ports:
     - containerPort: 80
       name: "web-server"
    volumeMounts:
    - name: web-data
      mountPath: /var/www/html/server/php/files
  volumes:
  - name: web-data
    persistentVolumeClaim:
      claimName: nfs-claim1
