kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
   name: px-fa-direct-access-snapshotclass
   annotations:
      snapshot.storage.kubernetes.io/is-default-class: "true"
driver: pxd.portworx.com
deletionPolicy: Delete
